//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalCarManagement.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBRentalCarEntity : DbContext
    {
        public DBRentalCarEntity()
            : base("name=DBRentalCarEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<attachments> attachments { get; set; }
        public virtual DbSet<cars> cars { get; set; }
        public virtual DbSet<customers> customers { get; set; }
        public virtual DbSet<payments> payments { get; set; }
        public virtual DbSet<reservations> reservations { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
