//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalCarManagement.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class payments
    {
        public System.Guid id { get; set; }
        public System.DateTime date { get; set; }
        public string payment_method { get; set; }
        public double amount { get; set; }
        public string description { get; set; }
        public System.Guid reservation_id { get; set; }
    
        public virtual reservations reservations { get; set; }
        public virtual reservations reservations1 { get; set; }
    }
}
